import { View } from "react-native";
import { Text } from "@/components/ui/typography";

function Section({ title, children }: { title: string; children: string }) {
  return (
    <View className="gap-1.5">
      <Text className="text-sm font-semibold text-neutral-900 dark:text-neutral-100">{title}</Text>
      <Text className="text-sm leading-5 text-neutral-500">{children}</Text>
    </View>
  );
}

/**
 * Real, SplitEven-specific privacy policy text (not placeholder copy) —
 * shared between the first-run acceptance gate ((auth)/privacy-policy.tsx)
 * and the read-only view reachable from Settings ((app)/privacy-policy.tsx).
 * Mirrored section-for-section in apps/web/src/app/privacy-policy/page.tsx —
 * keep both in sync when editing.
 */
export function PrivacyPolicyContent() {
  return (
    <View className="gap-5">
      <Text className="text-xs text-neutral-500">Last updated: October 2026</Text>

      <Section title="Introduction">
        This policy explains what information SplitEven collects, why, and what control you have over it.
        SplitEven is built and operated by a single independent developer, not a company with a dedicated
        legal or privacy team — but the same care applies: your financial data is treated as sensitive by
        default, is never sold, and is never used to build an advertising profile of you.
      </Section>

      <Section title="Information you provide directly">
        When you create an account: your email address and the password you choose (stored only as a
        salted hash we never see in plain text), plus an optional display name and profile photo. As you
        use the app: the groups you create or join, the expenses and settlements you log in those groups,
        and your personal accounts, transactions, budgets, and categories. Anything you type into a note,
        description, or category name is stored as you typed it.
      </Section>

      <Section title="Sign in with Google">
        {"If you choose \"Continue with Google\", SplitEven receives only your Google email address, name and profile picture from Google, and nothing else from your Google account. It is used solely to create and sign you in to your SplitEven account, is handled like any other account data described in this policy, and SplitEven's use of information received from Google APIs adheres to the Google API Services User Data Policy, including its Limited Use requirements. You can stop using Google sign-in any time by deleting your account."}
      </Section>

      <Section title="Information collected automatically">
        Basic technical data needed to run the app and keep it reliable: your device's push-notification
        token (only if you enable notifications), coarse device/OS information and crash reports sent
        through Sentry when something goes wrong (so bugs can be fixed), and standard request metadata
        (like timestamps) generated by using a hosted database. SplitEven does not use analytics or
        advertising trackers, does not read your contacts, and does not access your device's photo library
        except for the specific photo you choose to upload as an avatar or receipt.
      </Section>

      <Section title="How your information is used">
        Solely to run SplitEven: authenticating you, showing your balances, syncing group expenses with the
        people you split with, calculating your personal budgets and spending insights, and sending you a
        push notification when something relevant happens in a group you're part of (a new expense, a
        settlement, an invite). Crash reports are used only to find and fix bugs. Your financial data is
        never sold, rented, or used for advertising, and it is never used to train third-party AI models.
      </Section>

      <Section title="Where it's stored and who processes it">
        Your data is stored in a Supabase-hosted PostgreSQL database (Supabase acts as SplitEven's database
        and authentication provider), protected by row-level security policies so only you — and, for group
        data, the other members of that specific group — can read it. Crash and error reports are processed
        by Sentry. Push notifications are delivered through Expo's push notification service. Mobile app
        distribution and updates are handled through Apple's App Store and Google Play. None of these
        providers are permitted to use your data for their own purposes beyond providing their service to
        SplitEven.
      </Section>

      <Section title="Data retention">
        Your data is kept for as long as your account is active, so the app keeps working correctly (an
        expense from a year ago still needs to appear in your history). If you delete your account, your
        personal data is removed as described under "Your controls" below; some group-ledger data may
        persist in anonymized form so other members' shared history stays accurate.
      </Section>

      <Section title="Sharing with other users">
        Group data (expenses, balances, settlements, and the display name/photo you use in that group) is
        visible to the other members of that group — that's the point of a shared ledger, and something you
        agree to by joining or creating a group. Your personal accounts, categories, budgets, and personal
        (non-group) transactions are never shared with anyone, including other group members, regardless of
        which groups you're in together.
      </Section>

      <Section title="Sharing with third parties">
        SplitEven does not sell your data, and does not share it with third parties for their marketing
        purposes. Data is only shared with the infrastructure providers listed above (Supabase, Sentry,
        Expo, Apple, Google), strictly to operate the app, and only to the extent each provider needs to
        perform that specific function. Data may also be disclosed if required by law, such as in response
        to a valid legal request.
      </Section>

      <Section title="International data transfers">
        Because SplitEven relies on cloud infrastructure providers with servers in multiple regions, your
        data may be processed or stored in a country other than the one you're using the app from. Each
        provider used by SplitEven maintains its own security and compliance standards for cross-border data
        handling.
      </Section>

      <Section title="Security">
        Access to group and personal data is enforced at the database level through row-level security, so
        a request for someone else's data is rejected before it ever reaches the app. Passwords are hashed,
        never stored in plain text, and never visible to the developer. No system is perfectly secure,
        though — if you believe your account has been compromised, change your password immediately and
        contact us using the details below.
      </Section>

      <Section title="Your controls">
        You can export your personal ledger as a CSV at any time from Settings, and you can permanently
        delete your account from Settings as well. That disables your login and erases your personal
        accounts, transactions, budgets, and categories. Group expenses and settlements you were part of
        stay visible to your former group members (with your name replaced by "Deleted user") so their
        shared ledger isn't left broken — see Terms of Service for details. You can also update your
        display name, photo, and default currency at any time from Settings.
      </Section>

      <Section title="Children's privacy">
        SplitEven is not directed at children and is not intended for use by anyone under the age of 13 (or
        the minimum age required in your country to consent to data processing without parental approval).
        If you believe a child has created an account, contact us and it will be removed.
      </Section>

      <Section title="Changes to this policy">
        This policy may be updated as the app changes — for example, if a new feature collects a new kind of
        data. Material changes will be reflected here with an updated "Last updated" date, and continuing to
        use SplitEven after a change means you accept the revised policy.
      </Section>

      <Section title="Contact">
        Questions about this policy, or requests relating to your data, can be sent to
        jessanthony.tahil10@gmail.com.
      </Section>
    </View>
  );
}
